title: Sweet Shop Reaction Game
hero_image: images/banner.png
description: Turn a squidgy sweet into an input button for your Raspberry Pi
original_url: https://raspberrypi.org/learning/sweet-shop-reaction-game
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Create a sweet-munching sprite
- title: Wire up your sweet button
- title: Test the button
- title: Reaction game
- title: What next?
